
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.createdieselgenerators]
			chip_wood = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

	[types.leaves_type]

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			rainbow_birch = true
			snowblossom = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			yellow_autumn = true
			orange_autumn = true
			maple = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

	[types.cut_block_type]

		[types.cut_block_type.createdeco]
			pearl_brick = true
			short_pearl_brick = true
			tiled_pearl_brick = true
			long_pearl_brick = true
			corner_pearl_brick = true
			cracked_pearl_brick = true
			mossy_pearl_brick = true
			umber_brick = true
			short_umber_brick = true
			tiled_umber_brick = true
			long_umber_brick = true
			corner_umber_brick = true
			cracked_umber_brick = true
			mossy_umber_brick = true
			short_red_brick = true
			tiled_red_brick = true
			long_red_brick = true
			corner_red_brick = true
			cracked_red_brick = true
			mossy_red_brick = true
			verdant_brick = true
			short_verdant_brick = true
			tiled_verdant_brick = true
			long_verdant_brick = true
			corner_verdant_brick = true
			cracked_verdant_brick = true
			mossy_verdant_brick = true
			scarlet_brick = true
			short_scarlet_brick = true
			tiled_scarlet_brick = true
			long_scarlet_brick = true
			corner_scarlet_brick = true
			cracked_scarlet_brick = true
			mossy_scarlet_brick = true
			dusk_brick = true
			short_dusk_brick = true
			tiled_dusk_brick = true
			long_dusk_brick = true
			corner_dusk_brick = true
			cracked_dusk_brick = true
			mossy_dusk_brick = true
			dean_brick = true
			short_dean_brick = true
			tiled_dean_brick = true
			long_dean_brick = true
			corner_dean_brick = true
			cracked_dean_brick = true
			mossy_dean_brick = true
			blue_brick = true
			short_blue_brick = true
			tiled_blue_brick = true
			long_blue_brick = true
			corner_blue_brick = true
			cracked_blue_brick = true
			mossy_blue_brick = true

		[types.cut_block_type.mowziesmobs]
			painted_acacia = true

		[types.cut_block_type.createloveandwar]
			smooth_asphalt = true

		[types.cut_block_type.design_decor]
			black_metal_plate = true
			white_metal_plate = true
			blue_metal_plate = true
			light_blue_metal_plate = true
			red_metal_plate = true
			green_metal_plate = true
			lime_metal_plate = true
			pink_metal_plate = true
			magenta_metal_plate = true
			yellow_metal_plate = true
			gray_metal_plate = true
			light_gray_metal_plate = true
			brown_metal_plate = true
			cyan_metal_plate = true
			purple_metal_plate = true
			orange_metal_plate = true
			black_metal_sheet = true
			white_metal_sheet = true
			blue_metal_sheet = true
			light_blue_metal_sheet = true
			red_metal_sheet = true
			green_metal_sheet = true
			lime_metal_sheet = true
			pink_metal_sheet = true
			magenta_metal_sheet = true
			yellow_metal_sheet = true
			gray_metal_sheet = true
			light_gray_metal_sheet = true
			brown_metal_sheet = true
			cyan_metal_sheet = true
			purple_metal_sheet = true
			orange_metal_sheet = true
			metal_plate = true
			metal_sheet = true
			granite_castel_brick = true
			diorite_castel_brick = true
			andesite_castel_brick = true
			calcite_castel_brick = true
			dripstone_castel_brick = true
			deepslate_castel_brick = true
			tuff_castel_brick = true
			asurine_castel_brick = true
			crimsite_castel_brick = true
			limestone_castel_brick = true
			ochrum_castel_brick = true
			scoria_castel_brick = true
			scorchia_castel_brick = true
			veridium_castel_brick = true
			granite_castel_tile = true
			diorite_castel_tile = true
			andesite_castel_tile = true
			calcite_castel_tile = true
			dripstone_castel_tile = true
			deepslate_castel_tile = true
			tuff_castel_tile = true
			asurine_castel_tile = true
			crimsite_castel_tile = true
			limestone_castel_tile = true
			ochrum_castel_tile = true
			scoria_castel_tile = true
			scorchia_castel_tile = true
			veridium_castel_tile = true

		[types.cut_block_type.biomesoplenty]
			white_sandstone = true
			smooth_white_sandstone = true
			cut_white_sandstone = true
			orange_sandstone = true
			smooth_orange_sandstone = true
			cut_orange_sandstone = true
			black_sandstone = true
			smooth_black_sandstone = true
			cut_black_sandstone = true
			brimstone_brick = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.cut_block_type.ecologics]
			coconut = true
			seashell_tile = true
			ice_brick = true
			snow_brick = true
			walnut = true
			azalea = true
			flowering_azalea = true

		[types.cut_block_type.ad_astra]
			iron_plating = true
			steel_plating = true
			desh_plating = true
			ostrum_plating = true
			calorite_plating = true
			moon_stone = true
			moon_cobblestone = true
			moon_stone_brick = true
			polished_moon_stone = true
			aeronos = true
			strophar = true
			mars_stone = true
			mars_cobblestone = true
			mars_stone_brick = true
			polished_mars_stone = true
			mercury_stone = true
			mercury_cobblestone = true
			mercury_stone_brick = true
			polished_mercury_stone = true
			venus_stone = true
			venus_cobblestone = true
			venus_stone_brick = true
			polished_venus_stone = true
			venus_sandstone_brick = true
			glacio_stone = true
			glacio_cobblestone = true
			glacio_stone_brick = true
			polished_glacio_stone = true
			permafrost_brick = true
			chiseled_permafrost_brick = true
			polished_permafrost = true
			glacian = true

		[types.cut_block_type.tetra]
			forged_platform = true

		[types.cut_block_type.galosphere]
			silver_tiles = true
			silver_panel = true
			smooth_amethyst = true
			smooth_allurite = true
			smooth_lumiere = true
			amethyst_brick = true
			allurite_brick = true
			lumiere_brick = true
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true
			polished_pink_salt = true
			polished_rose_pink_salt = true
			polished_pastel_pink_salt = true
			pink_salt_brick = true
			rose_pink_salt_brick = true
			pastel_pink_salt_brick = true

		[types.cut_block_type.ad_astra_dh]
			rust_bricks = true
			polished_rust = true
			scrap_sand_bricks = true
			tiled_scrap_sand_bricks = true

		[types.cut_block_type.iceandfire]
			dread_stone = true

		[types.cut_block_type.festive_delight]
			gingerbread_block = true

		[types.cut_block_type.biomeswevegone]
			black_sandstone = true
			smooth_black_sandstone = true
			cut_black_sandstone = true
			white_sandstone = true
			smooth_white_sandstone = true
			cut_white_sandstone = true
			blue_sandstone = true
			smooth_blue_sandstone = true
			cut_blue_sandstone = true
			purple_sandstone = true
			smooth_purple_sandstone = true
			cut_purple_sandstone = true
			pink_sandstone = true
			smooth_pink_sandstone = true
			cut_pink_sandstone = true
			windswept_sandstone = true
			smooth_windswept_sandstone = true
			cut_windswept_sandstone = true
			dacite = true
			dacite_brick = true
			dacite_cobblestone = true
			dacite_tile = true
			red_rock = true
			red_rock_brick = true
			cracked_red_rock_brick = true
			chiseled_red_rock_brick = true
			mossy_red_rock_brick = true
			mossy_stone = true
			rocky_stone = true
			cattail_thatch = true
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.cut_block_type.create]
			copper_shingle = true
			exposed_copper_shingle = true
			weathered_copper_shingle = true
			oxidized_copper_shingle = true
			waxed_copper_shingle = true
			waxed_exposed_copper_shingle = true
			waxed_weathered_copper_shingle = true
			waxed_oxidized_copper_shingle = true
			copper_tile = true
			exposed_copper_tile = true
			weathered_copper_tile = true
			oxidized_copper_tile = true
			waxed_copper_tile = true
			waxed_exposed_copper_tile = true
			waxed_weathered_copper_tile = true
			waxed_oxidized_copper_tile = true
			cut_granite = true
			polished_cut_granite = true
			cut_granite_brick = true
			small_granite_brick = true
			cut_diorite = true
			polished_cut_diorite = true
			cut_diorite_brick = true
			small_diorite_brick = true
			cut_andesite = true
			polished_cut_andesite = true
			cut_andesite_brick = true
			small_andesite_brick = true
			cut_calcite = true
			polished_cut_calcite = true
			cut_calcite_brick = true
			small_calcite_brick = true
			cut_dripstone = true
			polished_cut_dripstone = true
			cut_dripstone_brick = true
			small_dripstone_brick = true
			cut_deepslate = true
			polished_cut_deepslate = true
			cut_deepslate_brick = true
			small_deepslate_brick = true
			cut_tuff = true
			polished_cut_tuff = true
			cut_tuff_brick = true
			small_tuff_brick = true
			cut_asurine = true
			polished_cut_asurine = true
			cut_asurine_brick = true
			small_asurine_brick = true
			cut_crimsite = true
			polished_cut_crimsite = true
			cut_crimsite_brick = true
			small_crimsite_brick = true
			cut_limestone = true
			polished_cut_limestone = true
			cut_limestone_brick = true
			small_limestone_brick = true
			cut_ochrum = true
			polished_cut_ochrum = true
			cut_ochrum_brick = true
			small_ochrum_brick = true
			cut_scoria = true
			polished_cut_scoria = true
			cut_scoria_brick = true
			small_scoria_brick = true
			cut_scorchia = true
			polished_cut_scorchia = true
			cut_scorchia_brick = true
			small_scorchia_brick = true
			cut_veridium = true
			polished_cut_veridium = true
			cut_veridium_brick = true
			small_veridium_brick = true

		[types.cut_block_type.create_confectionery]
			chocolate_bricks = true
			black_chocolate_bricks = true
			white_chocolate_bricks = true
			ruby_chocolate_brick = true
			caramel_bricks = true

		[types.cut_block_type.clayworks]
			terracotta = true
			white_terracotta = true
			orange_terracotta = true
			magenta_terracotta = true
			light_blue_terracotta = true
			yellow_terracotta = true
			lime_terracotta = true
			pink_terracotta = true
			gray_terracotta = true
			light_gray_terracotta = true
			cyan_terracotta = true
			purple_terracotta = true
			blue_terracotta = true
			brown_terracotta = true
			green_terracotta = true
			red_terracotta = true
			black_terracotta = true
			terracotta_brick = true
			white_terracotta_brick = true
			orange_terracotta_brick = true
			magenta_terracotta_brick = true
			light_blue_terracotta_brick = true
			yellow_terracotta_brick = true
			lime_terracotta_brick = true
			pink_terracotta_brick = true
			gray_terracotta_brick = true
			light_gray_terracotta_brick = true
			cyan_terracotta_brick = true
			purple_terracotta_brick = true
			blue_terracotta_brick = true
			brown_terracotta_brick = true
			green_terracotta_brick = true
			red_terracotta_brick = true
			black_terracotta_brick = true

		[types.cut_block_type.neapolitan]
			chocolate_brick = true
			chocolate_tile = true
			frond_thatch = true

		[types.cut_block_type.tfmg]
			hardened_planks = true
			factory_floor = true
			black_concrete = true
			white_concrete = true
			blue_concrete = true
			light_blue_concrete = true
			red_concrete = true
			green_concrete = true
			lime_concrete = true
			pink_concrete = true
			magenta_concrete = true
			yellow_concrete = true
			gray_concrete = true
			light_gray_concrete = true
			brown_concrete = true
			cyan_concrete = true
			purple_concrete = true
			orange_concrete = true
			concrete = true
			rebar_concrete = true
			cut_bauxite = true
			polished_cut_bauxite = true
			cut_bauxite_brick = true
			small_bauxite_brick = true
			cut_galena = true
			polished_cut_galena = true
			cut_galena_brick = true
			small_galena_brick = true

		[types.cut_block_type.ae2]
			sky_stone_brick = true
			sky_stone_small_brick = true
			smooth_quartz = true
			quartz_brick = true
			quartz_pillar = true

		[types.cut_block_type.snowyspirit]
			gingerbread = true

		[types.cut_block_type.quark]
			ancient_planks = true
			azalea_planks = true
			blossom_planks = true
			duskbound_block = true
			iron_plate = true
			rusty_iron_plate = true
			midori_block = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			permafrost = true
			permafrost_bricks = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			thatch = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true

		[types.cut_block_type.supplementaries]
			fine_wood = true
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.storagedrawers]
			trim = true
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.mcwbridges]
			log_bridge_stair = true
			rail_bridge = true
			bridge_pier = true
			rope_bridge = true
			rope_bridge_stair = true
			log_bridge_middle = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

		[entries.wood_type.refurbished_furniture]
			storage_cabinet = true
			storage_jar = true
			kitchen_cabinetry = true
			crate = true
			desk = true
			chair = true
			light_ceiling_fan = true
			cutting_board = true
			drawer = true
			table = true
			mail_box = true
			dark_ceiling_fan = true
			kitchen_sink = true
			toilet = true
			lattice_fence = true
			basin = true
			kitchen_drawer = true
			lattice_fence_gate = true
			bath = true
			kitchen_storage_cabinet = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.woodworks]
			leaf_pile = true

		[entries.leaves_type.refurbished_furniture]
			hedge = true

